name: seq2conn

channels:
  - pytorch
  - nvidia
  - pyg
  # - dglteam/label/cu118  # for DGL/CUDA 11.8
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - ipykernel
  - ipywidgets
  - pip
  - pytorch
  - pyg
  - pytorch-lightning
  - tensorboardX
  # - pytorch-cuda=11.8
  # - dgl
