name: seq2conn

channels:
  - pytorch
  - nvidia
  - dglteam/label/cu118
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - ipykernel
  - ipywidgets
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - pytorch-lightning
  - dgl
  - tensorboardX
